### ISSUE TITLE
EDSC search options stopped working again

### ISSUE THREAD

**Issue by grallewellyn** [MAAP-Project/Community#789]

**Comment by grallewellyn** [comment]
Cannot select a search param

**Comment by grallewellyn** [comment]
Also, see if can filter by time for maap.searchCollection

Test the use case Sam Niemoeller was asking about 

There will not be a way to get the full search query (bounding box, date range, collection ID) as python code? 
As feedback, I'm typically searching for 10s/100s/1000s of granules at a time, so clicking on each individual granule adds in too much human error + time to be very useful for me. If other MAAP users find this feature useful, great! But otherwise there's no need to prioritize it for me; I'll keep using my current workflow, no stress.

**Comment by grallewellyn** [comment]
The first problem with edsc is that the dit earthdata search proxy isn't working, so I am using the ops earthdata search proxy which does work. The other problem which I believe is unrelated is a problem that I have seen before: 
The event listener isn't being triggered when the user adds a dataset. I know it should be working because it's the same code that worked in the past, and if I do a postMessage somewhere else in the code, the event listener is triggered. 
I saw this error last on April 20th of this error, but then a week later the code started working again with no code changes on my part 

If I try changing the edsc_server to be https://ade.ops.maap-project.org:30052/search (instead of the dit one), then the print statement 'edsc url changed' is printed everytime I add or remove a collection. That print statement isn't in our edsc jupyter extension code, but I know something is being triggered to print 'edsc url changed' even though our event listener isn't being triggered 
Does anyone know what could have changed to have the event listener not be triggered anymore for edsc jupyter extension? 

Code that Brian sent that I am going to look at that could potentially be causing the error: https://github.com/MAAP-Project/maap-eclipseche-ops/blob/master/edsc-proxy/edsc-proxy.conf#L144-L161

George also requested to be added to this ticket

**Comment by oddes** [comment]
@grallewellyn and @gchang 
I still see the same issue:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenR5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bf26795bdd2abddf3cf4e019f0d31c97643a7361/Screenshot%202023-10-25%20at%204.08.48%20PM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenh5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3c44453bc8beb193d719b9be098d4a20308b417d/Screenshot%202023-10-25%20at%204.09.58%20PM.png)

**Comment by grallewellyn** [comment]
This would be the same problem as: https://github.com/MAAP-Project/Community/issues/803#issuecomment-1780166710
